server:
  port: 8180
spring:
  application:
    name: dubbo-provider
dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
    # 使用默认的命名空间
    #parameters:
    #  namespace: 7931ebad-b34c-43ed-b886-420267cc4937
  application:
    name: dubbo-provider #应用名
  protocol:
    name: dubbo #dubbo协议
    port: 20880 #协议端口
  scan:
    base-packages: cn.newbeedaly #扫包范围
  provider:
    timeout: 30000 #超时时间

